# Generated by Django 3.2.3 on 2021-05-25 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zju_id', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=20)),
                ('role', models.CharField(max_length=1)),
                ('hashed_password', models.CharField(max_length=30)),
                ('token', models.CharField(max_length=30)),
                ('last_login', models.DateTimeField()),
            ],
        ),
    ]
