# Generated by Django 3.2.3 on 2021-05-25 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info_mgt', '0002_auto_20210525_1243'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='capacity',
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('term', models.CharField(choices=[('AW', 'Autumn and winter semester'), ('SS', 'Spring and summer semester'), ('SP', 'Spring term'), ('SU', 'Summer term'), ('AU', 'Autumn term'), ('WI', 'Winter term'), ('SH', 'Short term')], max_length=2)),
                ('day', models.IntegerField()),
                ('capacity', models.IntegerField()),
                ('start_rank', models.IntegerField()),
                ('end_rank', models.IntegerField()),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info_mgt.course')),
            ],
        ),
    ]
