# Generated by Django 3.2.3 on 2021-06-25 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info_mgt', '0003_rename_major_teacher_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='memberCnt',
            field=models.IntegerField(default=0),
        ),
    ]
