# Generated by Django 3.2.3 on 2021-05-25 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info_mgt', '0003_auto_20210525_1424'),
    ]

    operations = [
        migrations.RenameField(
            model_name='class',
            old_name='course_id',
            new_name='course',
        ),
    ]
