# Generated by Django 3.2.3 on 2021-05-25 15:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('info_mgt', '0004_rename_course_id_class_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='day',
        ),
        migrations.RemoveField(
            model_name='class',
            name='end_rank',
        ),
        migrations.RemoveField(
            model_name='class',
            name='start_rank',
        ),
        migrations.AddField(
            model_name='class',
            name='duration',
            field=models.CharField(default=django.utils.timezone.now, max_length=15),
            preserve_default=False,
        ),
    ]
