# Generated by Django 3.2.3 on 2021-05-27 01:03

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('info_mgt', '0005_auto_20210525_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='capacity',
            field=models.IntegerField(null=True, blank=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='duration',
            field=models.CharField(null=True, blank=True, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(null=True, blank=True, on_delete=django.db.models.deletion.CASCADE, to='info_mgt.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='term',
            field=models.CharField(choices=[('AW', 'Autumn and winter semester'), ('SS', 'Spring and summer semester'), ('SP', 'Spring term'), ('SU', 'Summer term'), ('AU', 'Autumn term'), ('WI', 'Winter term'), ('SH', 'Short term')], null=True, blank=True, max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='year',
            field=models.IntegerField(null=True, blank=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='zju_id',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.DeleteModel(
            name='Class',
        ),
    ]
