# Generated by Django 3.2.3 on 2021-05-27 02:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info_mgt', '0006_auto_20210527_0103'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='teacher',
        ),
        migrations.RemoveField(
            model_name='course',
            name='term',
        ),
        migrations.RemoveField(
            model_name='course',
            name='year',
        ),
        migrations.AlterField(
            model_name='course',
            name='capacity',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course',
            name='duration',
            field=models.CharField(default='', max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='zju_id',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('term', models.CharField(choices=[('AW', 'Autumn and winter semester'), ('SS', 'Spring and summer semester'), ('SP', 'Spring term'), ('SU', 'Summer term'), ('AU', 'Autumn term'), ('WI', 'Winter term'), ('SH', 'Short term')], max_length=2)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info_mgt.course')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info_mgt.user')),
            ],
        ),
    ]
