# Generated by Django 3.2.3 on 2021-05-27 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info_mgt', '0007_auto_20210527_0205'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info_mgt.campus')),
            ],
        ),
        migrations.CreateModel(
            name='Major',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info_mgt.department')),
            ],
        ),
        migrations.RemoveField(
            model_name='course',
            name='major',
        ),
        migrations.CreateModel(
            name='MajorHasCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_type', models.CharField(choices=[('C', 'compulsory'), ('N', 'non-compulsory')], default='N', max_length=1)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info_mgt.course')),
                ('major', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info_mgt.major')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='info_mgt.department'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='major',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='info_mgt.major'),
        ),
    ]
