# Generated by Django 3.2.3 on 2021-06-21 06:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('info_mgt', '0003_rename_major_teacher_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.CharField(max_length=256)),
                ('file_size', models.DecimalField(decimal_places=2, max_digits=19)),
                ('file_name', models.CharField(max_length=100)),
                ('file_type', models.CharField(max_length=10)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info_mgt.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AssignmentGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_path', models.CharField(max_length=256)),
                ('assignment_result', models.IntegerField(blank=True, null=True)),
                ('course', models.ManyToManyField(to='info_mgt.Course')),
                ('student', models.ManyToManyField(to='info_mgt.Student')),
            ],
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_start', models.DateTimeField()),
                ('assignment_end', models.DateTimeField()),
                ('assignment_intro', models.TextField()),
                ('assignment_ratio', models.IntegerField(blank=True, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info_mgt.course')),
            ],
        ),
    ]
