# Generated by Django 3.2.4 on 2021-06-26 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('info_mgt', '0003_rename_major_teacher_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.CharField(blank=True, max_length=256, null=True)),
                ('file_size', models.BigIntegerField(blank=True, null=True)),
                ('file_name', models.CharField(max_length=100)),
                ('file_type', models.CharField(choices=[(1, '文件'), (2, '文件夹')], max_length=10)),
                ('parent', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='AssignmentGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_path', models.CharField(max_length=256)),
                ('assignment_result', models.IntegerField(blank=True, null=True)),
                ('Class', models.ManyToManyField(to='info_mgt.Class')),
                ('course', models.ManyToManyField(to='info_mgt.Course')),
                ('student', models.ManyToManyField(to='info_mgt.Student')),
            ],
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_name', models.CharField(max_length=20, null=True)),
                ('assignment_start', models.DateTimeField()),
                ('assignment_end', models.DateTimeField()),
                ('assignment_intro', models.TextField()),
                ('assignment_ratio', models.IntegerField(blank=True, null=True)),
                ('Class', models.ManyToManyField(to='info_mgt.Class')),
                ('course', models.ManyToManyField(to='info_mgt.Course')),
            ],
        ),
    ]
