# Generated by Django 3.2.4 on 2021-06-26 15:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('info_mgt', '0003_rename_major_teacher_department'),
        ('resource_share', '0002_alter_source_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='Class',
            field=models.ManyToManyField(to='info_mgt.Class'),
        ),
        migrations.AddField(
            model_name='source',
            name='course',
            field=models.ManyToManyField(to='info_mgt.Course'),
        ),
        migrations.AddField(
            model_name='source',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
