# Generated by Django 3.2.4 on 2021-06-11 06:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('info_mgt', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='试卷名')),
                ('generate_time', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info_mgt.course')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('0', '选择题'), ('1', '判断题')], default='选择题', max_length=20, verbose_name='题目类型')),
                ('content', models.TextField()),
                ('answer', models.CharField(choices=[('0', 'A'), ('1', 'B'), ('2', 'C'), ('3', 'D'), ('4', 'T'), ('5', 'F')], default='A', max_length=2, verbose_name='题目答案')),
                ('value', models.FloatField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info_mgt.course')),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('courses', models.ManyToManyField(to='info_mgt.Course')),
                ('students', models.ManyToManyField(to='info_mgt.Student')),
                ('teachers', models.ManyToManyField(to='info_mgt.Teacher')),
            ],
        ),
        migrations.CreateModel(
            name='StudentAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_right', models.BooleanField()),
                ('score', models.FloatField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='online_exam.question')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info_mgt.student')),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('score', models.FloatField()),
                ('weight', models.FloatField()),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='online_exam.paper')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info_mgt.student')),
            ],
        ),
        migrations.AddField(
            model_name='paper',
            name='questions',
            field=models.ManyToManyField(to='online_exam.Question'),
        ),
        migrations.AddField(
            model_name='paper',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info_mgt.teacher'),
        ),
    ]
