# Generated by Django 3.2.4 on 2021-06-11 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_exam', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='chapter',
            field=models.IntegerField(default=1),
        ),
    ]
