# Generated by Django 3.2.4 on 2021-06-22 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('online_exam', '0002_question_chapter'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='paper',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='online_exam.paper'),
        ),
    ]
