# Generated by Django 3.2.3 on 2021-06-21 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('info_mgt', '0003_rename_major_teacher_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_performance', models.IntegerField(blank=True, null=True)),
                ('exam_result', models.IntegerField(blank=True, null=True)),
                ('final_result', models.IntegerField(blank=True, null=True)),
                ('course', models.ManyToManyField(to='info_mgt.Course')),
                ('student', models.ManyToManyField(to='info_mgt.Student')),
            ],
        ),
    ]
