# Generated by Django 3.2.3 on 2021-06-22 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info_mgt', '0003_rename_major_teacher_department'),
        ('grade_mgt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseresult',
            name='Class',
            field=models.ManyToManyField(to='info_mgt.Class'),
        ),
    ]
