# Generated by Django 3.2.3 on 2021-06-22 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grade_mgt', '0002_courseresult_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseresult',
            name='is_submit',
            field=models.BooleanField(null=True),
        ),
    ]
